### ISSUE TITLE
masterブランチのDockerイメージのビルドが落ちる

### ISSUE THREAD

**Issue by Rush2929** [ElementX-Network/WaterdogPE-Docker#2]
## なぜ:
* [Java17を必要](https://github.com/WaterdogPE/WaterdogPE/commit/937cdc6098cec2b7d61af62c587b7de75fa2616c)としてるけど[Java11でビルド](https://github.com/ElementX-Network/WaterdogPE-Docker/blob/8d6fa1b36e939c8950e5116d2338544001747fde/Dockerfile#L1)しようとしているから

**Comment by fuyutsuki** [comment]
このissue解決するまで一旦workflow無効化
